name: Jest + Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          config-file: cypress/cypress.config.ts
          start: npm run jest, npm run cy:run
      # - name: Jest run
      #   uses: willcaul/jest-github-action@v2
      #   with:
      #     coverage-comment: false
      #     working-directory: 'jest'
      #     test-command: npm run jest
