name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          config-file: cypress/cypress.config.ts
          start: npm run cy:run

  jest-run:
    runs-on: ubuntu-latest
      - name: Checkout
        uses: actions/checkout@v2
    steps:
      - name: Jest run
        uses: stefanoeb/jest-action@1.0.3
